### PR TITLE
Fix unreachable overload check.

### PR DESCRIPTION
**Pull request by castano**
This fixes the unreacheable overload_set check and also fixes a crash when the identifier is not a function, but something else (for example a struct). I don't understand this assert, though:

// assert(identifier->type_info == compiler->type_void);

I would expect the type of the identifier to be FUNCTION, but seems to be VOID. Is that to be expected?

### CODE REVIEW

**Comment by machinamentum** [comment]
>I would expect the type of the identifier to be FUNCTION, but seems to be VOID. Is that to be expected?
This is expected. When an overload_set is generated, the type of the identifier is set to VOID for sanity's sake (and since we dont actually know what the type of the identifier resolves to). The code that handles Ast_Function_Call will fixup the type here once overloading resolution passes.

**Comment by machinamentum** [comment]
Merged, thanks!

**Comment by machinamentum** [comment]
This actually subtly broke function pointers since they do not generate an overload_set. I've opted to check the type of the subexpression in the fall-through case instead. See: 5ead4aea71d23362c4a1cf68d81f737ee9980d36

**Comment by castano** [comment]
Ah, thanks for clarifying!

**Pull request merged**
