### PR TITLE
feat: add linux get executable path

### PR DESCRIPTION
**Pull request by ahmadrosid**
Note: I have been tested with my ubuntu 19 i'm not sure in other distro.

### CODE REVIEW

**Comment by machinamentum** [comment]
A few comments:

This implementation of get_executable_path is subtly incorrect. [readlink](http://man7.org/linux/man-pages/man2/readlink.2.html) returns the number of bytes stored in _buf_ on success. The if-statement should read:
> if (result < 0) return to_string("");

This implementation is not portable across implementations of Unix. /proc/self/exe is notably a Linux thing, please move the function outside the #ifdef UNIX ... #endif section into a new section for Linux (UNIX is also defined on macOS so this change would already introduce a build error there). The definition to check for is LINUX.

free(path.data) should not be disabled here. get_executable_path is supposed to return a new string every single time, and path is not used after the mprintf call (the substring containing the path to the jiyu folder is copied into a new buffer in mprintf). If there is crashing or a bug happening here, let me know!

Additionally, please squash your commits after these changes have been made.

Thanks!

**Comment by machinamentum** [comment]
> This implementation of get_executable_path is subtly incorrect. [readlink](http://man7.org/linux/man-pages/man2/readlink.2.html) returns the number of bytes stored in _buf_ on success. The if-statement should read:
> 
> > if (result < 0) return to_string("");

After thinking about this, I am also wrong. This should return an empty String:
> if (result < 0) return String();

This would explain any crashing that may have occurred when trying to free the result from get_executable_path. I've made this change to the macOS version in 3b8afcd789f3863e0f949ea6cc537ad3a0589415 and suggest the same change be made here too.

**Comment by ahmadrosid** [comment]
Ok @machinamentum let my try first.

**Comment by ahmadrosid** [comment]
Working perfectly here @machinamentum :+1:

**Comment by machinamentum** [comment]
Looks good to me. Merged, thanks!

**Pull request merged**
